# Generated by Django 5.2.1 on 2025-06-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField()),
                ('doi', models.URLField(blank=True)),
                ('semiconductor_material', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('breakdown_voltage', models.FloatField()),
                ('r_on_area', models.FloatField()),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='references/')),
            ],
        ),
    ]
