# Generated by Django 5.2.1 on 2025-06-03 19:18

######
# Config template for db
######

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='author',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='r_on_area',
        ),
        migrations.AddField(
            model_name='devicedata',
            name='company_university',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='first_author',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='part_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='r_on',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='r_on_at_25C',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='rated_current',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='rated_voltage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='breakdown_voltage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='journal',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='semiconductor_material',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='year',
            field=models.IntegerField(default=1900),
        ),
    ]
