# Generated by Django 5.2.1 on 2025-06-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main_app', '0002_remove_devicedata_author_remove_devicedata_r_on_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, default='', max_length=255)),
                ('br_voltage', models.JSONField(blank=True, default=list)),
                ('r_on', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
