# Generated by Django 5.2.3 on 2025-06-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main_app', '0003_materiallimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiallimit',
            name='br_voltage',
        ),
        migrations.RemoveField(
            model_name='materiallimit',
            name='r_on',
        ),
        migrations.AddField(
            model_name='materiallimit',
            name='Ec',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='materiallimit',
            name='epsilon',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='materiallimit',
            name='miu',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
